apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-weather-api  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-weather-api
  template:
    metadata:
      labels:
        app: aks-weather-api
    spec:
      containers:
      - name: aks-weather-api
        image: acrkiikubernetespaygdevtest.azurecr.io/weatherapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aks-weather-api
  name: aks-weather-api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: aks-weather-api
  type: ClusterIP